kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ~/hdfs-k8s/namenode
    containerPath: /mnt/hdfs/namenode
  - hostPath: ~/hdfs-k8s/datanode1
    containerPath: /mnt/hdfs/datanode1
- role: worker
  extraMounts:
  - hostPath: ~/hdfs-k8s/datanode2
    containerPath: /mnt/hdfs/datanode2
