apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-datanode1
spec:
  serviceName: "hadoop-datanode1"
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-datanode1
  template:
    metadata:
      labels:
        app: hadoop-datanode1
    spec:
      containers:
      - name: datanode1
        image: bde2020/hadoop-datanode:latest
        ports:
        - containerPort: 9864
        volumeMounts:
        - name: pvc-datanode1
          mountPath: "/mnt/hdfs/datanode1"
  volumeClaimTemplates:
  - metadata:
      name: pvc-datanode1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
