apiVersion: apps/v1
kind: Deployment                # ressource types
metadata:
  name: kafka
spec:
  replicas: 1                   # Number of replicas (instances)
  selector:
    matchLabels:
      app: kafka                # Sélection to find K8s pods
  template:                     # Template for pods
    metadata:
      labels:
        app: kafka              # labels assigned to pods
    spec:
      containers:               
      - name: kafka             
        image: confluentinc/cp-kafka:latest # image used
        ports:
        - containerPort: 9092   
        environment:            # kafka env vars
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181" 
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092" 
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"           
