apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=true
    clientPort=2181
    clientPortAddress=0.0.0.0
    server.1=zookeeper-0.zookeeper:2888:3888
    server.2=zookeeper-1.zookeeper:2888:3888
    server.3=zookeeper-2.zookeeper:2888:3888
